import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import LayoutTheme from "@/components/layout-theme";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children } ) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* 🌟 Inject color theme immediately */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('color-theme') || 'default';
                  document.documentElement.setAttribute('data-theme', theme);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          <LayoutTheme defaultTheme="dark">
            {children}
          </LayoutTheme>
      </body>
    </html>
  );
}
